export const LOGOS = {
    docker: "/logo/docker.svg",
    "c#": "/logo/c--.svg",
    figma: "/logo/figma.svg",
    git: "/logo/git.svg",
    gmail: "/logo/gmail.svg",
    graphql: "/logo/graphql.svg",
    java: "/logo/java.svg",
    javascript: "/logo/javascript.svg",
    js: "/logo/javascript.svg",
    kafka: "/logo/kafka.svg",
    linkedin: "/logo/linkedin.svg",
    nextjs: "/logo/nextjs.svg",
    next: "/logo/nextjs.svg",
    nodejs: "/logo/Nodejs.svg",
    node: "/logo/Nodejs.svg",
    python: "/logo/python-5.svg",
    react: "/logo/React.svg",
    reactjs: "/logo/React.svg",
    redux: "/logo/redux.svg",
    spring: "/logo/spring.svg",
    typescript: "/logo/typescript.svg",
    ts: "/logo/typescript.svg",
    zabbix: "/logo/zabbix.svg",
    angular: "/logo/angular.svg",
    markdown: "/logo/markdown.svg"
};
