export const LOGOS = {
    docker: "/logo/docker.svg",
    "C#": "/logo/c--.svg",
    figma: "/logo/figma.svg",
    git: "/logo/git.svg",
    gmail: "/logo/gmail.svg",
    graphql: "/logo/graphql.svg",
    java: "/logo/java.svg",
    javascript: "/logo/javascript.svg",
    kafka: "/logo/kafka.svg",
    linkedin: "/logo/linkedin.svg",
    nextjs: "/logo/nextjs.svg",
    nodejs: "/logo/Nodejs.svg",
    python: "/logo/python-5.svg",
    react: "/logo/React.svg",
    redux: "/logo/redux.svg",
    spring: "/logo/spring.svg",
    typescript: "/logo/typescript.svg",
    zabbix: "/logo/zabbix.svg",
};
